spring.application.name=cms

server.port = 8081

# jpa configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# sql configurations
spring.datasource.url=jdbc:mysql://localhost:3306/cms
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# spring.security.user.name=${SECURITY_USERNAME}
# spring.security.user.password=${SECURITY_PASSWORD}