spring.application.name=cms

server.port = ${PORT}

# jpa configurations
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# sql configurations
spring.datasource.url=${DB_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect